name: Code Review

on:
  pull_request:
    types: [opened, reopened, synchronize]

env:
  webhook_url: ${{ secrets.WEBHOOK }}

permissions:
  contents: read
  pull-requests: write

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: anc95/ChatGPT-CodeReview@main
        env:
          MODEL: gpt-3.5-turbo
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          LANGUAGE: Korean

      - name: notification to swit
        uses: roharon/action-swit@v1
        with:
          webhooks_url: ${{ env.webhook_url }}
          MESSAGE: "🏷 ${{ job.status }} 프론트 OpenAI 코드 리뷰 : Catcher-web - by ${{ github.actor }}"