name: Code Review

on:
  pull_request:
    types: [opened, reopened, synchronize]

env:
  WEBHOOK_URL: ${{ secrets.WEBHOOK }}
  GIT_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}

permissions:
  contents: read
  pull-requests: write

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: anc95/ChatGPT-CodeReview@main
        env:
          MODEL: gpt-3.5-turbo
          GITHUB_TOKEN: ${{ env.GITHUB_TOKEN }}
          OPENAI_API_KEY: ${{ env.OPENAI_API_KEY }}
          LANGUAGE: Korean

      - name: Send Notification
        if: ${{ always() }}
        run: |
          if [[ ${{ job.status }} == "success" ]]; then
            MESSAGE="✅ ${{ job.status }} 프론트 OpenAI 코드 리뷰 : Catcher-service - by ${{ github.actor }}"
          else
            MESSAGE="❌ ${{ job.status }} 프론트 OpenAI 코드 리뷰 : Catcher-service - by ${{ github.actor }}"
          fi
          curl -X POST -H "Content-Type: application/json" --data "{\"text\":\"${MESSAGE}\"}" ${{ env.WEBHOOK_URL }}