name: CI nextjs

on:
  push:
    branches: [ "feat/add-dockerfile" ]

env:
  ecr_url: ${{ secrets.ECR_REPO_DEV_FRONT }}
  role_arn: ${{ secrets.OIDC_ROLE }}
  aws_region: ${{ secrets.AWS_REGION }}

permissions:
  id-token: write   # This is required for requesting the JWT
  contents: read    # This is required for actions/checkout

jobs:
  build:
    name: To push ECR
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 1

      - name: Docker build
        run: docker build -t catcher-web .
        
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-region: ${{ env.aws_region }}
          role-session-name: GitHubActions
          role-to-assume: ${{ env.role_arn }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Publish Image to ECR(CATCHER-WEB)
        run: |
          docker tag catcher-web:latest ${{ env.ecr_url }}:catcher-web
          docker push ${{ env.ecr_url }}:catcher-web
