name: ON PR/Merge - Check Errors | Build

on:
  pull_request:
    branches: [ "develop", "main" ]
  push:
    branches: [ "develop", "main", "refactor-jdb-gitaction-workflow" ]

jobs:
  merged:
    if: github.event.pull_request.merged == true
    name: Build Nextjs
    uses: ./.github/workflows/front.yml
    secrets:
      ECR_URL: ${{ secrets.ECR_REPO_DEV_FRONT }}
      ROLE_ARN: ${{ secrets.OIDC_ROLE }}
      AWS_REGION: ${{ secrets.AWS_REGION }}
      WEBHOOK_URL: ${{ secrets.WEBHOOK }}

  pr:
    if: ${{ github.event.pull_request.merged == false && github.event == 'push'}}
    name: Error Check
    uses: ./.github/workflows/check_err.yml

  # pushed-1:
  #   if: ${{ github.event.pull_request.merged == false && github.event != 'push'}}
  #   name: Error Check
  #   uses: ./.github/workflows/check_err.yml

  pushed-2:
    if: ${{ github.event.pull_request.merged == false && github.event != 'push'}}
    name: Build Nextjs
    uses: ./.github/workflows/front.yml
    secrets:
      ECR_URL: ${{ secrets.ECR_REPO_DEV_FRONT }}
      ROLE_ARN: ${{ secrets.OIDC_ROLE }}
      AWS_REGION: ${{ secrets.AWS_REGION }}
      WEBHOOK_URL: ${{ secrets.WEBHOOK }}
    # needs: pushed-1